import {
  AfroWoman,
  BrandName,
  Danger,
  FifthWoman,
  FourWoman,
  Logo,
  SecondAfroWoman,
  SecondWoman,
  ThirdWoman,
} from "../../assets/images/images";

export const dresses = [
  {
    id: 1,
    title: "Elegant Afro Chic",
    cost: 120,
    size: "M",
    status: "available",
    isFavorite: false,
    image: AfroWoman,
  },
  {
    id: 2,
    title: "Bold Confidence",
    cost: 135,
    size: "L",
    status: "limited",
    isFavorite: false,
    image: SecondAfroWoman,
  },
  {
    id: 3,
    title: "Urban Radiance",
    cost: 110,
    size: "S",
    status: "available",
    isFavorite: false,
    image: SecondWoman,
  },
  {
    id: 4,
    title: "Serene Grace",
    cost: 140,
    size: "M",
    status: "out of stock",
    isFavorite: false,
    image: ThirdWoman,
  },
  {
    id: 5,
    title: "Power in Red",
    cost: 160,
    size: "L",
    status: "available",
    isFavorite: false,
    image: Danger,
  },
  {
    id: 6,
    title: "Golden Glow",
    cost: 150,
    size: "S",
    status: "limited",
    isFavorite: false,
    image: FifthWoman,
  },
  {
    id: 7,
    title: "Mystic Harmony",
    cost: 130,
    size: "M",
    status: "available",
    isFavorite: false,
    image: FourWoman,
  },
  {
    id: 8,
    title: "Minimal Square",
    cost: 95,
    size: "XS",
    status: "available",
    isFavorite: false,
    image: Logo,
  },
  {
    id: 9,
    title: "Studio Signature",
    cost: 100,
    size: "M",
    status: "out of stock",
    isFavorite: false,
    image: BrandName,
  },
];
